apiVersion: v2
name: low-code-vinyl
description: A helm chart for a low-code vinyl (records) management platform
type: application
version: 0.1.0
appVersion: "1.16.0"
maintainers:
  - name: Mickey
    email: kyle.mickey@gmail.com
sources:
  - https://github.com/badasstronaut/low-code-vinyl
dependencies:
  # Adapted from appsmith's helm chart https://github.com/appsmithorg/appsmith/blob/release/deploy/helm/Chart.yaml
  - condition: redis.enabled
    name: redis
    version: 17.0.10
    repository: https://charts.bitnami.com/bitnami
  - condition: mongodb.enabled
    name: mongodb
    version: 10.31.5
    repository: https://charts.bitnami.com/bitnami
